#동물 보호소에 들어온 동물의 이름이 몇개인지 조회 (NULL 제외, 중복 제외)
# SELECT COUNT(DISTINCT NAME) AS "count" FROM ANIMAL_INS WHERE NAME IS NOT NULL;

# MySQL의 경우 서브쿼리로 만든 테이블의 이름을 지정해줘야 해서 COUNTNAME으로 명시함
SELECT COUNT(*) AS "count" FROM (SELECT NAME FROM ANIMAL_INS WHERE NAME IS NOT NULL GROUP BY NAME) COUNTNAME;